flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-0.11.2.0
- http2-1.6.0
- servant-0.7
- servant-server-0.7
- text-1.2.2.1
- warp-3.2.6
arch: x86_64
package-indices:
- name: Hackage
  git: https://github.com/commercialhaskell/all-cabal-hashes.git
  http: https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz
  download-prefix: https://s3.amazonaws.com/hackage.fpcomplete.com/package/
resolver: lts-5.15
